process.inc :
	ln -s submicron.inc process.inc
	@echo
	@echo "Using a simple generic process file"
	@echo "This may not be what you want."
	@echo "If you have a file of model parameters for the process you're"
	@echo "using, you should:"
	@echo
	@echo "rm process.inc"
	@echo "ln -s real_process_file process.inc"
	@echo
	@echo "Replace real_process_file above with the actual name, of course."
 
